In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Accident_Information.csv")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20328\708539461.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Accident_Information.csv")

In [3]:
df["Accident_Severity"].value_counts()

Accident_Severity
Slight     1734548
Serious     286339
Fatal        26369
Name: count, dtype: int64

In [4]:
df.isnull().sum()

Accident_Index                                       0
1st_Road_Class                                       0
1st_Road_Number                                      2
2nd_Road_Class                                  844272
2nd_Road_Number                                  17593
Accident_Severity                                    0
Carriageway_Hazards                            2007807
Date                                                 0
Day_of_Week                                          0
Did_Police_Officer_Attend_Scene_of_Accident        278
Junction_Control                                     0
Junction_Detail                                      0
Latitude                                           174
Light_Conditions                                     0
Local_Authority_(District)                           0
Local_Authority_(Highway)                            0
Location_Easting_OSGR                              164
Location_Northing_OSGR                             164
Longitude                                          175
LSOA_of_Accident_Location                       144953
Number_of_Casualties                                 0
Number_of_Vehicles                                   0
Pedestrian_Crossing-Human_Control                 2920
Pedestrian_Crossing-Physical_Facilities           3560
Police_Force                                         0
Road_Surface_Conditions                              0
Road_Type                                            0
Special_Conditions_at_Site                     1995137
Speed_limit                                         37
Time                                               156
Urban_or_Rural_Area                                  0
Weather_Conditions                                   0
Year                                                 0
InScotland                                          53
dtype: int64

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("Accident_Information.csv").iloc[:100000]

# Handle missing values
# Fill or drop missing values based on column importance
df = df.dropna(subset=['Accident_Index', 'Date', 'Time',])  # Drop rows with critical missing data
df['Speed_limit'].fillna(df['Speed_limit'].mean(), inplace=True)
df['Year'] = df['Year'].astype(int)
df['Speed_limit'] = df['Speed_limit'].astype(int)
df['Day_of_Week'] = df['Day_of_Week'].str.lower()
df['Weather_Conditions'] = df['Weather_Conditions'].str.lower()
df['Special_Conditions_at_Site'].fillna('none', inplace=True)
df['Junction_Control'] = df['Junction_Control'].apply(lambda x: np.random.choice(['Auto traffic signal', 'Give way or uncontrolled']) if x == 'Data missing or out of range' else x)

df.drop(columns=["Carriageway_Hazards","Date","Time","Local_Authority_(Highway)","Accident_Index","1st_Road_Number","2nd_Road_Class","2nd_Road_Number","Did_Police_Officer_Attend_Scene_of_Accident","Latitude","Location_Easting_OSGR","Location_Northing_OSGR","Longitude","LSOA_of_Accident_Location","Number_of_Casualties","Number_of_Vehicles","Police_Force","Year","InScotland"], inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20328\1477569461.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Accident_Information.csv").iloc[:100000]
C:\Users\ASUS\AppData\Local\Temp\ipykernel_20328\1477569461.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Speed_limit'].fillna(df['Speed_limit'].mean(), inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_20328\1477569461.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Special_Conditions_at_Site'].fillna('none', inplace=True)

In [6]:
df.columns

Index(['1st_Road_Class', 'Accident_Severity', 'Day_of_Week',
       'Junction_Control', 'Junction_Detail', 'Light_Conditions',
       'Local_Authority_(District)', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Road_Surface_Conditions',
       'Road_Type', 'Special_Conditions_at_Site', 'Speed_limit',
       'Urban_or_Rural_Area', 'Weather_Conditions'],
      dtype='object')

In [7]:
df.isna().sum()

1st_Road_Class                              0
Accident_Severity                           0
Day_of_Week                                 0
Junction_Control                            0
Junction_Detail                             0
Light_Conditions                            0
Local_Authority_(District)                  0
Pedestrian_Crossing-Human_Control          12
Pedestrian_Crossing-Physical_Facilities    16
Road_Surface_Conditions                     0
Road_Type                                   0
Special_Conditions_at_Site                  0
Speed_limit                                 0
Urban_or_Rural_Area                         0
Weather_Conditions                          0
dtype: int64

In [8]:
df = df.dropna(subset=['Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities'])

In [9]:
df.head(5)

,1st_Road_Class,Accident_Severity,Day_of_Week,Junction_Control,Junction_Detail,Light_Conditions,Local_Authority_(District),Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Road_Surface_Conditions,Road_Type,Special_Conditions_at_Site,Speed_limit,Urban_or_Rural_Area,Weather_Conditions
0,A,Serious,tuesday,Give way or uncontrolled,Not at junction or within 20 metres,Daylight,Kensington and Chelsea,0.0,1.0,Wet or damp,Single carriageway,none,30,Urban,raining no high winds
1,B,Slight,wednesday,Auto traffic signal,Crossroads,Darkness - lights lit,Kensington and Chelsea,0.0,5.0,Dry,Dual carriageway,none,30,Urban,fine no high winds
2,C,Slight,thursday,Auto traffic signal,Not at junction or within 20 metres,Darkness - lights lit,Kensington and Chelsea,0.0,0.0,Dry,Single carriageway,none,30,Urban,fine no high winds
3,A,Slight,friday,Auto traffic signal,Not at junction or within 20 metres,Daylight,Kensington and Chelsea,0.0,0.0,Dry,Single carriageway,none,30,Urban,fine no high winds
4,Unclassified,Slight,monday,Auto traffic signal,Not at junction or within 20 metres,Darkness - lighting unknown,Kensington and Chelsea,0.0,0.0,Wet or damp,Single carriageway,none,30,Urban,fine no high winds

In [10]:
# Save the cleaned data to a new CSV file
df.to_csv('cleaned_dataset.csv', index=False)

In [11]:
df["Accident_Severity"].value_counts()

Accident_Severity
Slight     86322
Serious    12418
Fatal       1235
Name: count, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('cleaned_dataset.csv')
# Initialize the encoder
encoder = LabelEncoder()

# List of categorical columns
categorical_columns = [
    '1st_Road_Class', 'Day_of_Week', 'Junction_Control', 
    'Junction_Detail', 'Light_Conditions', 'Local_Authority_(District)', 
    'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities', 
    'Road_Surface_Conditions', 'Road_Type', 'Special_Conditions_at_Site', 
    'Urban_or_Rural_Area', 'Weather_Conditions'
]

for column in categorical_columns:
    df[column] = encoder.fit_transform(df[column])
    # Print out the mapping for each column
    print(f"Mapping for column: {column}")
    print(dict(zip(encoder.classes_, range(len(encoder.classes_)))))
    print('-' * 50)

Mapping for column: 1st_Road_Class
{'A': 0, 'A(M)': 1, 'B': 2, 'C': 3, 'Motorway': 4, 'Unclassified': 5}
--------------------------------------------------
Mapping for column: Day_of_Week
{'friday': 0, 'monday': 1, 'saturday': 2, 'sunday': 3, 'thursday': 4, 'tuesday': 5, 'wednesday': 6}
--------------------------------------------------
Mapping for column: Junction_Control
{'Authorised person': 0, 'Auto traffic signal': 1, 'Give way or uncontrolled': 2, 'Not at junction or within 20 metres': 3, 'Stop sign': 4}
--------------------------------------------------
Mapping for column: Junction_Detail
{'Crossroads': 0, 'Data missing or out of range': 1, 'Mini-roundabout': 2, 'More than 4 arms (not roundabout)': 3, 'Not at junction or within 20 metres': 4, 'Other junction': 5, 'Private drive or entrance': 6, 'Roundabout': 7, 'Slip road': 8, 'T or staggered junction': 9}
--------------------------------------------------
Mapping for column: Light_Conditions
{'Darkness - lighting unknown': 0, 'Darkness - lights lit': 1, 'Darkness - lights unlit': 2, 'Darkness - no lighting': 3, 'Daylight': 4}
--------------------------------------------------
Mapping for column: Local_Authority_(District)
{'Allerdale': 0, 'Alnwick': 1, 'Amber Valley': 2, 'Ashfield': 3, 'Barking and Dagenham': 4, 'Barnet': 5, 'Barnsley': 6, 'Barrow-in-Furness': 7, 'Bassetlaw': 8, 'Berwick-upon-Tweed': 9, 'Bexley': 10, 'Birmingham': 11, 'Blackburn with Darwen': 12, 'Blackpool': 13, 'Blyth Valley': 14, 'Bolsover': 15, 'Bolton': 16, 'Bradford': 17, 'Brent': 18, 'Bridgnorth': 19, 'Bromley': 20, 'Bromsgrove': 21, 'Burnley': 22, 'Bury': 23, 'Calderdale': 24, 'Camden': 25, 'Cannock Chase': 26, 'Carlisle': 27, 'Castle Morpeth': 28, 'Chester': 29, 'Chester-le-Street': 30, 'Chesterfield': 31, 'Chorley': 32, 'City of London': 33, 'Congleton': 34, 'Copeland': 35, 'Coventry': 36, 'Craven': 37, 'Crewe and Nantwich': 38, 'Croydon': 39, 'Darlington': 40, 'Derby': 41, 'Derbyshire Dales': 42, 'Derwentside': 43, 'Doncaster': 44, 'Dudley': 45, 'Durham': 46, 'Ealing': 47, 'Easington': 48, 'East Riding of Yorkshire': 49, 'East Staffordshire': 50, 'Eden': 51, 'Ellesmere Port and Neston': 52, 'Enfield': 53, 'Erewash': 54, 'Fylde': 55, 'Gateshead': 56, 'Greenwich': 57, 'Hackney': 58, 'Halton': 59, 'Hambleton': 60, 'Hammersmith and Fulham': 61, 'Haringey': 62, 'Harrogate': 63, 'Harrow': 64, 'Hartlepool': 65, 'Havering': 66, 'Herefordshire, County of': 67, 'High Peak': 68, 'Hillingdon': 69, 'Hounslow': 70, 'Hyndburn': 71, 'Islington': 72, 'Kensington and Chelsea': 73, 'Kingston upon Hull, City of': 74, 'Kingston upon Thames': 75, 'Kirklees': 76, 'Knowsley': 77, 'Lambeth': 78, 'Lancaster': 79, 'Leeds': 80, 'Lewisham': 81, 'Lichfield': 82, 'Liverpool': 83, 'London Airport (Heathrow)': 84, 'Macclesfield': 85, 'Malvern Hills': 86, 'Manchester': 87, 'Mansfield': 88, 'Merton': 89, 'Middlesbrough': 90, 'Newark and Sherwood': 91, 'Newcastle upon Tyne': 92, 'Newcastle-under-Lyme': 93, 'Newham': 94, 'North East Derbyshire': 95, 'North East Lincolnshire': 96, 'North Lincolnshire': 97, 'North Shropshire': 98, 'North Tyneside': 99, 'North Warwickshire': 100, 'Nuneaton and Bedworth': 101, 'Oldham': 102, 'Oswestry': 103, 'Pendle': 104, 'Preston': 105, 'Redbridge': 106, 'Redcar and Cleveland': 107, 'Redditch': 108, 'Ribble Valley': 109, 'Richmond upon Thames': 110, 'Richmondshire': 111, 'Rochdale': 112, 'Rossendale': 113, 'Rotherham': 114, 'Rugby': 115, 'Rushcliffe': 116, 'Ryedale': 117, 'Salford': 118, 'Sandwell': 119, 'Scarborough': 120, 'Sedgefield': 121, 'Sefton': 122, 'Selby': 123, 'Sheffield': 124, 'Shrewsbury and Atcham': 125, 'Solihull': 126, 'South Derbyshire': 127, 'South Lakeland': 128, 'South Ribble': 129, 'South Shropshire': 130, 'South Staffordshire': 131, 'South Tyneside': 132, 'Southwark': 133, 'St. Helens': 134, 'Stafford': 135, 'Staffordshire Moorlands': 136, 'Stockport': 137, 'Stockton-on-Tees': 138, 'Stoke-on-Trent': 139, 'Stratford-upon-Avon': 140, 'Sunderland': 141, 'Sutton': 142, 'Tameside': 143, 'Tamworth': 144, 'Teesdale': 145, 'Telford and Wrekin': 146, 'Tower Hamlets': 147, 'Trafford': 148, 'Tynedale': 149, 'Vale Royal': 150, 'Wakefield': 151, 'Walsall': 152, 'Waltham Forest': 153, 'Wandsworth': 154, 'Wansbeck': 155, 'Warrington': 156, 'Warwick': 157, 'Wear Valley': 158, 'West Lancashire': 159, 'Westminster': 160, 'Wigan': 161, 'Wirral': 162, 'Wolverhampton': 163, 'Worcester': 164, 'Wychavon': 165, 'Wyre': 166, 'Wyre Forest': 167, 'York': 168}
--------------------------------------------------
Mapping for column: Pedestrian_Crossing-Human_Control
{np.float64(0.0): 0, np.float64(1.0): 1, np.float64(2.0): 2}
--------------------------------------------------
Mapping for column: Pedestrian_Crossing-Physical_Facilities
{np.float64(0.0): 0, np.float64(1.0): 1, np.float64(4.0): 2, np.float64(5.0): 3, np.float64(7.0): 4, np.float64(8.0): 5}
--------------------------------------------------
Mapping for column: Road_Surface_Conditions
{'Data missing or out of range': 0, 'Dry': 1, 'Flood over 3cm. deep': 2, 'Frost or ice': 3, 'Snow': 4, 'Wet or damp': 5}
--------------------------------------------------
Mapping for column: Road_Type
{'Dual carriageway': 0, 'One way street': 1, 'Roundabout': 2, 'Single carriageway': 3, 'Slip road': 4, 'Unknown': 5}
--------------------------------------------------
Mapping for column: Special_Conditions_at_Site
{'Auto signal part defective': 0, 'Auto traffic signal - out': 1, 'Data missing or out of range': 2, 'Mud': 3, 'Oil or diesel': 4, 'Road sign or marking defective or obscured': 5, 'Road surface defective': 6, 'Roadworks': 7, 'none': 8}
--------------------------------------------------
Mapping for column: Urban_or_Rural_Area
{'Rural': 0, 'Unallocated': 1, 'Urban': 2}
--------------------------------------------------
Mapping for column: Weather_Conditions
{'fine + high winds': 0, 'fine no high winds': 1, 'fog or mist': 2, 'other': 3, 'raining + high winds': 4, 'raining no high winds': 5, 'snowing + high winds': 6, 'snowing no high winds': 7, 'unknown': 8}
--------------------------------------------------

In [13]:
y = df['Accident_Severity']
X = df.drop('Accident_Severity', axis=1)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
X_test

,1st_Road_Class,Day_of_Week,Junction_Control,Junction_Detail,Light_Conditions,Local_Authority_(District),Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Road_Surface_Conditions,Road_Type,Special_Conditions_at_Site,Speed_limit,Urban_or_Rural_Area,Weather_Conditions
83773,0,0,2,4,1,119,0,0,1,0,8,40,2,1
50642,5,5,2,9,4,38,0,0,1,3,8,30,0,1
53794,0,3,1,4,4,132,0,5,1,3,8,30,2,1
84695,5,2,2,9,4,126,0,0,1,3,8,30,2,1
91072,0,2,1,4,3,165,0,0,1,0,8,70,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6006,0,6,1,9,4,147,0,3,1,3,8,30,2,1
27687,0,0,2,7,4,51,0,3,1,2,8,30,0,1
44178,0,0,2,9,1,16,0,0,5,3,8,30,2,5
32373,5,3,2,5,1,71,0,0,1,3,8,30,2,1
43947,0,2,2,3,4,16,0,0,5,0,8,30,2,1

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

X_train

array([[ 1.34984486, -0.48077559,  0.57083235, ..., -0.51709274,
         0.55641393, -0.41647469],
       [-0.95813966, -0.96477055,  0.57083235, ..., -0.51709274,
         0.55641393, -0.41647469],
       [-0.95813966, -1.44876551,  0.57083235, ..., -0.51709274,
         0.55641393, -0.41647469],
       ...,
       [-0.95813966,  1.45520425, -1.39435236, ..., -0.51709274,
         0.55641393, -0.41647469],
       [-0.95813966,  0.97120929, -1.39435236, ..., -0.51709274,
         0.55641393, -0.41647469],
       [ 1.34984486,  0.97120929,  0.57083235, ..., -0.51709274,
         0.55641393, -0.41647469]])

In [17]:
import pickle
pickle.dump(scaler, open('scaler.pkl', 'wb'))

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, auc

In [19]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lg_classifier = LogisticRegression()

lg_classifier.fit(X_train, y_train)

pickle.dump(lg_classifier, open('./models/lg_classifier.pkl', 'wb'))

y_test_pred = lg_classifier.predict(X_test)

lg_score_unseen = accuracy_score(y_test, y_test_pred)
print('The Accuracy score for Logistic Regression on unseen data: ', lg_score_unseen)

The Accuracy score for Logistic Regression on unseen data:  0.860415103775944

In [20]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier()

dt_classifier.fit(X_train, y_train)

pickle.dump(dt_classifier, open('./models/dt_classifier.pkl', 'wb'))

y_test_pred = dt_classifier.predict(X_test)

dt_score_unseen = accuracy_score(y_test, y_test_pred)
print('The Accuracy score for Decision tree on unseen data: ', dt_score_unseen)

The Accuracy score for Decision tree on unseen data:  0.7562390597649412

In [21]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
rf_classifier = RandomForestClassifier(n_estimators = 100)

rf_classifier.fit(X_train, y_train)
pickle.dump(rf_classifier, open('./models/rf_classifier.pkl', 'wb'))
y_test_pred = rf_classifier.predict(X_test)

rf_score_unseen = accuracy_score(y_test, y_test_pred)
print('The Accuracy score for Random Forest on unseen data: ', rf_score_unseen)

The Accuracy score for Random Forest on unseen data:  0.8293573393348337

In [22]:
# Gradient Boosting Classifier
gb_classifier = GradientBoostingClassifier()
gb_classifier.fit(X_train, y_train)
pickle.dump(gb_classifier, open('./models/gb_classifier.pkl', 'wb'))
y_pred = gb_classifier.predict(X_test)
gb_score_unseen = accuracy_score(y_test, y_pred)
print('The Accuracy score for  Gradient Boosting on unseen data : ', gb_score_unseen)

The Accuracy score for  Gradient Boosting on unseen data :  0.8604651162790697

In [23]:
# K Neighbours Classifier
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)

with open('./models/knn_classifier.pkl', 'wb') as file:
    pickle.dump(knn_classifier, file)

y_pred = knn_classifier.predict(X_test)
KNN_score_unseen = accuracy_score(y_test, y_pred)
print('The Accuracy score for KNN_Classifier on unseen data : ', KNN_score_unseen)

The Accuracy score for KNN_Classifier on unseen data :  0.8432108027006752

In [24]:
# XGBoost
from xgboost import XGBClassifier
encoder.fit(y_train)  # Fit on training labels
y_train_encoded = encoder.transform(y_train)  # Transform the training labels
y_test_encoded = encoder.transform(y_test)  # Transform the test labels

# Display the mappings for y_train and y_test
print("Mapping for y_train:")
print(dict(zip(encoder.classes_, range(len(encoder.classes_)))))

print("\nMapping for y_test:")
print(dict(zip(encoder.classes_, range(len(encoder.classes_)))))

xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train, y_train_encoded)

with open('./models/xgb_classifier.pkl', 'wb') as file:
    pickle.dump(xgb_classifier, file)

y_pred = xgb_classifier.predict(X_test)
XGB_score_unseen = accuracy_score(y_test_encoded, y_pred)
print('The Accuracy score for XGB_Classifier on unseen data : ', XGB_score_unseen)

Mapping for y_train:
{'Fatal': 0, 'Serious': 1, 'Slight': 2}

Mapping for y_test:
{'Fatal': 0, 'Serious': 1, 'Slight': 2}
The Accuracy score for XGB_Classifier on unseen data :  0.8422105526381596

In [28]:
import pickle
import os

folder_dir = './models'
estimators = []

for file in os.listdir(folder_dir):
    model_name = file.replace("_classifier.pkl","")
    model_dir = os.path.join(folder_dir,file)
    model = pickle.load(open(model_dir, 'rb'))
    estimators.append((model_name, model))

In [29]:
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

In [33]:
voting_clf_hard = VotingClassifier(estimators=estimators, voting='hard')
voting_clf_hard.fit(X_train, y_train)

y_pred_hard = voting_clf_hard.predict(X_test)
acc_hard = accuracy_score(y_test, y_pred_hard)
print("Hard Voting Accuracy:", acc_hard)

pickle.dump(voting_clf_hard, open('./models/voting_classifier.pkl', 'wb'))

Hard Voting Accuracy: 0.8562140535133783